"""turnstiles, groups and users table

Revision ID: d41d04bf3dbe
Revises: 
Create Date: 2020-07-12 00:14:11.010267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41d04bf3dbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turnstile_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('total_rate', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location')
    )
    op.create_index(op.f('ix_turnstile_group_group_id'), 'turnstile_group', ['group_id'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('turnstile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turnstile_id', sa.String(length=64), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=True),
    sa.Column('turn_rate', sa.Float(), nullable=True),
    sa.Column('group_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['turnstile_group.group_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turnstile_turnstile_id'), 'turnstile', ['turnstile_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turnstile_turnstile_id'), table_name='turnstile')
    op.drop_table('turnstile')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_turnstile_group_group_id'), table_name='turnstile_group')
    op.drop_table('turnstile_group')
    # ### end Alembic commands ###
